{
 "title": "Star Media's workplace Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(nodejs_active_handles_total,DeploymentName)"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_online{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Away",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_away{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "DDP Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Metrics Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_metrics_requests{DeploymentName=\"$deployment\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rocketchat_metrics_size{DeploymentName=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Handles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_requests_total{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (space) (nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"})",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "Per pod heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} [{{space}}]"
      }
     ]
    },
    {
     "title": "GC - Seconds Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_pause_seconds_total{DeploymentName=\"$deployment\"}[5m])) by (gctype)",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC - Bytes Freed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total{DeploymentName=\"$deployment\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\"}[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  {
   "title": "RocketChat Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(rocketchat_message_sent{DeploymentName=\"$deployment\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages Sent Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Users Presence",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rocketchat_users_online{DeploymentName=\"$deployment\"})",
       "legendFormat": "Online"
      },
      {
       "expr": "avg(rocketchat_users_away{DeploymentName=\"$deployment\"})",
       "legendFormat": "Away"
      }
     ]
    },
    {
     "title": "Users & Sessions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})",
       "legendFormat": "Connected Users"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_count{DeploymentName=\"$deployment\"})",
       "legendFormat": "All Sessions"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_auth{DeploymentName=\"$deployment\"})",
       "legendFormat": "Authenticated Sessions "
      }
     ]
    },
    {
     "title": "Oplog",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_oplog{DeploymentName=\"$deployment\"}[5m])) by (collection,op)",
       "legendFormat": "{{collection}}/{{op}}"
      }
     ]
    },
    {
     "title": "Oplog Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketchat_oplog_queue{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Push Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rocketchat_push_queue{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Meteor Facts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_facts{DeploymentName=\"$deployment\"}) by (pkg, fact)",
       "legendFormat": "{{pkg}} {{fact}}"
      }
     ]
    },
    {
     "title": "Total of Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})",
       "legendFormat": "Users"
      }
     ]
    },
    {
     "title": "Total of Rooms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})",
       "legendFormat": "Rooms"
      }
     ]
    },
    {
     "title": "Notifications / Minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_notification_sent{DeploymentName=\"$deployment\"}[5m])) by (notification_type)",
       "legendFormat": "{{notification_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{DeploymentName=\"$deployment\"}) by (method) * sum(increase(rocketchat_meteor_methods_count{DeploymentName=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{DeploymentName=\"$deployment\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count{DeploymentName=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{DeploymentName=\"$deployment\"}) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count{DeploymentName=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{DeploymentName=\"$deployment\"}) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count{DeploymentName=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks{DeploymentName=\"$deployment\"}) by (callback) * sum(increase(rocketchat_callbacks_count{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_hooks{DeploymentName=\"$deployment\"}) by (hook) * sum(increase(rocketchat_hooks_count{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api{DeploymentName=\"$deployment\"}) by (entrypoint) * sum(increase(rocketchat_rest_api_count{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}